Merge branch 'master' into ausias/rpc-backup-failover

diff --git a/charts/cluster-hoprd/templates/cronjob-upload-hoprd-logs.yaml b/charts/cluster-hoprd/templates/cronjob-upload-hoprd-logs.yaml
--- a/charts/cluster-hoprd/templates/cronjob-upload-hoprd-logs.yaml
+++ b/charts/cluster-hoprd/templates/cronjob-upload-hoprd-logs.yaml
@@ -94,6 +94,14 @@ spec:
                 fi
                 sleep 1200 # wait 20 minutes for the node to resync
                 kubectl wait --for=condition=available deployment/{{ .Values.logs.upload.sourceNode }} --timeout=120m
+                corrupted_channels=$(curl -s -X 'GET' 'http://{{ .Values.logs.upload.sourceNode }}-p2p-tcp:3001/api/v4/channels/corrupted' -H 'accept: application/json' -H "X-Auth-Token: $HOPRD_API_TOKEN")
+                if [[ $(jq -r '.channelIds | length' <<<"$corrupted_channels") -gt 0 ]]; then
+              else
+                  echo "Channels are still corrupted after resync, aborting log upload. You might consider changing the RPC provider"
+                  exit 1
+                fi
+              else
+                echo "No corrupted channels found, proceeding with log upload"
               fi
 
           resources:
